import type { Metadata } from "next";
import { ArrowUpRight, Bell, Bookmark, CheckCircle2, FileText, Sparkles } from "lucide-react";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { JobCard } from "@/components/job-card";
import { seekerSummary } from "@/data/workspace";

export const metadata: Metadata = { title: "Seeker dashboard", description: "Track profile strength, recommended roles, and applications." };

export default function SeekerDashboardPage() {
  return <AppShell active="seeker"><div className="workspace-header"><div><p className="eyebrow">Seeker workspace</p><h1>Good momentum, Sarah.</h1><p>Your profile, recommendations, and applications are ready for live Supabase data.</p></div><Link className="button button-primary" href="/jobs">Find roles <ArrowUpRight size={17} /></Link></div><div className="workspace-grid"><section className="workspace-panel hero-panel" id="profile"><div><Sparkles size={22} /><p className="eyebrow">Profile match</p><h2>{seekerSummary.matchScore}%</h2><p>{seekerSummary.profileStrength} profile strength for senior product roles in the Gulf.</p></div><div className="profile-meter" aria-label={`${seekerSummary.matchScore}% profile match`}><span style={{ width: `${seekerSummary.matchScore}%` }} /></div></section><section className="workspace-panel"><div className="panel-title"><h2>Today</h2><Bell size={19} /></div><ul className="compact-list"><li><CheckCircle2 size={17} />Nexa Commerce moved you to interview.</li><li><Bookmark size={17} />3 saved searches have fresh matches.</li><li><FileText size={17} />CV preview is ready for secure storage wiring.</li></ul></section></div><section className="workspace-section"><div className="panel-title"><div><h2>Recommended roles</h2><p>Demo data now, public Supabase jobs later.</p></div><Link className="arrow-link" href="/jobs">View all jobs <ArrowUpRight size={16} /></Link></div><div className="job-grid">{seekerSummary.recommendedJobs.map((job) => <JobCard key={job.id} job={job} />)}</div></section><section className="workspace-section" id="applications"><div className="panel-title"><h2>Applications</h2><span className="status-pill">3 active</span></div><div className="data-table" role="table" aria-label="Application tracking"><div role="row"><strong role="columnheader">Role</strong><strong role="columnheader">Company</strong><strong role="columnheader">Stage</strong><strong role="columnheader">Updated</strong></div>{seekerSummary.applications.map((application) => <div key={`${application.company}-${application.role}`} role="row"><span role="cell">{application.role}</span><span role="cell">{application.company}</span><span role="cell"><mark>{application.stage}</mark></span><span role="cell">{application.updated}</span></div>)}</div></section></AppShell>;
}
