import type { Metadata } from "next";
import { Building2, Globe2, MapPin, Pencil } from "lucide-react";
import { SectionCard, WorkspaceHeader } from "@/components/workspace-ui";
import { employerSummary } from "@/data/workspace";

export const metadata: Metadata = { title: "Company profile" };
export default function CompanyProfilePage() { const company = employerSummary.company; return <><WorkspaceHeader eyebrow="Company profile" title={employerSummary.organization} description="This is the employer organization profile: public brand, company details, contact information, media, and hiring identity." action={{ href: "/employer/company", label: "Edit company" }} />
  <section className="company-profile-overview"><span className="company-logo">NC</span><div><h2>{company.industry}</h2><p><MapPin size={15} /> {company.location} · {company.size}</p><span>{company.followers} followers · {company.following} following</span></div><div className="profile-completion"><strong>{company.completeness}%</strong><span>Company profile complete</span></div></section>
  <div className="workspace-content-grid"><SectionCard title="About" action={<button className="text-button"><Pencil size={14} /> Edit</button>}><p className="body-copy">{company.description}</p></SectionCard><SectionCard title="Company details"><div className="detail-list"><div><Building2 size={17} /><span>Size</span><strong>{company.size}</strong></div><div><Globe2 size={17} /><span>Website</span><strong>{company.website}</strong></div><div><MapPin size={17} /><span>Headquarters</span><strong>{company.location}</strong></div></div></SectionCard></div>
  <SectionCard title="Brand and media" description="Logo, cover image, gallery, public posts, contact details, and social links are managed here."><div className="media-placeholder"><Building2 size={28} /><strong>Company media library</strong><p>Add workplace photos, team imagery, and brand assets to strengthen the public employer profile.</p><button className="filter-button">Manage media</button></div></SectionCard></>; }
