import type { Metadata } from "next";
import { ArrowUpRight, BriefcaseBusiness, CalendarDays, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { employerSummary } from "@/data/workspace";

export const metadata: Metadata = { title: "Employer dashboard", description: "Manage vacancies, applicants, interviews, and hiring pipeline." };

export default function EmployerDashboardPage() {
  return <AppShell active="employer"><div className="workspace-header"><div><p className="eyebrow">Employer workspace</p><h1>{employerSummary.organization} hiring desk.</h1><p>Vacancies, applicants, and interviews are staged for the live organization permissions model.</p></div><button className="button button-primary" type="button" disabled>Create vacancy</button></div><section className="metric-grid" aria-label="Hiring metrics"><article><BriefcaseBusiness size={20} /><strong>{employerSummary.openRoles}</strong><span>Open roles</span></article><article><UsersRound size={20} /><strong>{employerSummary.newApplicants}</strong><span>New applicants</span></article><article><CalendarDays size={20} /><strong>{employerSummary.interviews}</strong><span>Interviews</span></article></section><section className="workspace-section" id="pipeline"><div className="panel-title"><div><h2>Applicant pipeline</h2><p>Demo candidates show the target ATS density for desktop work.</p></div><span className="status-pill">Live sync pending</span></div><div className="pipeline-board">{employerSummary.pipeline.map((candidate) => <article key={candidate.name} className="candidate-card"><div className="candidate-avatar">{candidate.name.split(" ").map((part) => part[0]).join("")}</div><div><h3>{candidate.name}</h3><p>{candidate.role}</p><span>{candidate.stage}</span></div><strong>{candidate.score}%</strong></article>)}</div></section><section className="workspace-section" id="vacancies"><div className="panel-title"><h2>Vacancies</h2><button className="filter-button" type="button" disabled>Filters</button></div><div className="data-table" role="table" aria-label="Vacancy management"><div role="row"><strong role="columnheader">Role</strong><strong role="columnheader">Status</strong><strong role="columnheader">Applicants</strong><strong role="columnheader">Updated</strong></div>{employerSummary.vacancies.map((vacancy) => <div key={vacancy.title} role="row"><span role="cell">{vacancy.title}</span><span role="cell"><mark>{vacancy.status}</mark></span><span role="cell">{vacancy.applicants}</span><span role="cell">{vacancy.updated}</span></div>)}</div></section><section className="workspace-section" id="company"><div className="panel-title"><div><h2>Company profile</h2><p>Branding, members, credits, and billing land here after access is available.</p></div><ArrowUpRight size={18} /></div></section></AppShell>;
}
