import type { Metadata } from "next";
import { FileText, MapPin, Pencil, UserRound } from "lucide-react";
import { InfoList, SectionCard, WorkspaceHeader } from "@/components/workspace-ui";
import { seekerSummary } from "@/data/workspace";

export const metadata: Metadata = { title: "My profile" };
export default function SeekerProfilePage() { const profile = seekerSummary.profile; return <><WorkspaceHeader eyebrow="Personal profile" title={seekerSummary.name} description="This is your person profile: experience, education, skills, CV, preferences, and public career identity." action={{ href: "/seeker/profile", label: "Edit profile" }} />
  <section className="profile-overview"><div className="profile-avatar"><UserRound size={28} /></div><div><h2>{profile.headline}</h2><p><MapPin size={15} /> {seekerSummary.location} · {seekerSummary.availability}</p><span>{profile.followers} followers · {profile.following} following</span></div><div className="profile-completion"><strong>{profile.completeness}%</strong><span>Profile complete</span></div></section>
  <div className="workspace-content-grid"><SectionCard title="About" action={<button className="text-button" type="button"><Pencil size={14} /> Edit</button>}><p className="body-copy">Product designer focused on commerce, design systems, and thoughtful experiences for teams across the Gulf.</p></SectionCard><SectionCard title="CV / résumé" action={<button className="text-button" type="button">Replace</button>}><div className="file-row"><FileText size={20} /><div><strong>Sarah-Ahmed-CV.pdf</strong><p>{profile.cvStatus}</p></div><button className="filter-button" type="button">View</button></div></SectionCard></div>
  <div className="profile-columns profile-columns-wide"><InfoList title="Experience" values={profile.experience} /><InfoList title="Education" values={profile.education} /><InfoList title="Skills" values={profile.skills} /><InfoList title="Languages" values={profile.languages} /><InfoList title="Certifications & licenses" values={profile.certifications} /><InfoList title="Links" values={["LinkedIn", "Portfolio", "GitHub"]} /></div>
  <SectionCard title="Personal details & job preferences" description="Nationality, visa, salary, relocation, driving license, and profile visibility are managed separately from the company profile."><div className="detail-list detail-list-grid"><div><span>Desired salary</span><strong>AED 28,000 / month</strong></div><div><span>Visa status</span><strong>UAE resident</strong></div><div><span>Relocation</span><strong>Open to relocate</strong></div><div><span>Driving license</span><strong>Yes</strong></div></div></SectionCard></>; }
