import type { Metadata } from "next";
import { ShieldCheck, UserPlus } from "lucide-react";
import { PreviewActionButton } from "@/components/interaction-ui";
import { SectionCard, WorkspaceHeader } from "@/components/workspace-ui";
import { employerSummary } from "@/data/workspace";

export const metadata: Metadata = { title: "Team and permissions" };
export default function TeamPage() { return <><WorkspaceHeader eyebrow="Organization access" title="Team & permissions" description="Invite colleagues and control company-level hiring permissions." />
  <SectionCard title="Members" description="Owner, recruiter, hiring manager, and viewer roles remain organization-scoped."><div className="member-list">{employerSummary.members.map((member) => <article key={member.email}><span className="candidate-avatar">{member.name.slice(0, 2)}</span><div><strong>{member.name}</strong><p>{member.email}</p></div><span className="status-pill">{member.role}</span><PreviewActionButton type="button" className="text-button" storageKey={`employer-team-manage-${member.email}`} successLabel="Updated">Manage</PreviewActionButton></article>)}</div></SectionCard>
  <div className="workspace-content-grid"><SectionCard title="Invite a colleague"><form className="inline-form"><input type="email" name="email" required placeholder="colleague@company.com" /><select name="role" defaultValue="Recruiter"><option>Recruiter</option><option>Hiring manager</option><option>Viewer</option></select><PreviewActionButton type="button" className="button button-primary button-small" storageKey="employer-team-invite" pendingLabel="Sending…" successLabel="Invite sent"><UserPlus size={15} /> Send invite</PreviewActionButton></form></SectionCard><SectionCard title="Permission model"><div className="dashboard-callout"><ShieldCheck size={20} /><div><strong>Organization-scoped access</strong><p>Members only see the company, jobs, candidates, and billing capabilities assigned to their role.</p></div></div></SectionCard></div></>; }
