import { ArrowLeft, Apple, Check } from "lucide-react";
import { cookies } from "next/headers";
import Link from "next/link";
import { Logo } from "@/components/logo";
import { isLocale } from "@/lib/i18n";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ mode?: string }> }) {
  const [params, cookieStore] = await Promise.all([searchParams, cookies()]);
  const localeValue = cookieStore.get("ts-locale")?.value;
  const locale = isLocale(localeValue) ? localeValue : "en";
  const signup = params.mode === "signup";
  return <main className="auth-page"><section className="auth-brand"><Link className="back-link auth-back" href="/"><ArrowLeft size={17} />Back</Link><div className="auth-brand-copy"><Logo inverted /><p className="eyebrow">{locale === "ar" ? "طموحك يبدأ هنا" : "Ambition starts here"}</p><h1>{signup ? "Make your next move count." : "Welcome back to what’s next."}</h1><ul><li><Check size={18} />A profile that works harder for you</li><li><Check size={18} />Relevant roles from growing teams</li><li><Check size={18} />Every application, clearly tracked</li></ul></div></section><section className="auth-form-wrap"><form className="auth-form" method="post"><p className="eyebrow">{signup ? "Create your account" : "Your account"}</p><h2>{signup ? "Join TalentSouq" : "Log in"}</h2><p>{signup ? "Start as a job seeker or employer. Supabase auth wiring is the next implementation step." : "Continue your search or get back to hiring once Supabase auth is connected."}</p>{signup && <fieldset className="role-choice"><legend>I’m here to</legend><label><input type="radio" name="role" defaultChecked /><span>Find work</span></label><label><input type="radio" name="role" /><span>Hire talent</span></label></fieldset>}<label className="field"><span>Email address</span><input type="email" name="email" autoComplete="email" required placeholder="you@example.com" /></label><label className="field"><span>Password</span><input type="password" name="password" autoComplete={signup ? "new-password" : "current-password"} required minLength={8} placeholder="At least 8 characters" /></label><button className="button button-primary button-full" type="submit" disabled aria-describedby="auth-form-note">{signup ? "Connect Supabase to create accounts" : "Connect Supabase to log in"}</button><div className="form-divider"><span>or continue with</span></div><div className="social-buttons"><button className="button button-secondary" type="button" disabled>Google</button><button className="button button-secondary" type="button" disabled><Apple size={18} />Apple</button></div><p className="switch-auth">{signup ? "Already have an account?" : "New to TalentSouq?"} <Link href={signup ? "/auth/login" : "/auth/login?mode=signup"}>{signup ? "Log in" : "Join now"}</Link></p><p className="form-note" id="auth-form-note">Authentication wiring begins when the Supabase project URL, publishable key, callback URLs, and auth policies are supplied. The disabled buttons prevent demo credentials from being submitted before that connection exists.</p></form></section></main>;
}
